

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class Secondpage extends javax.swing.JFrame {
static ImageIcon i1;
public static JLabel l3;
static String str;
    /**
     * Creates new form Secondpage
     */
    public Secondpage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BMW Cars", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 3, 18), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel1.setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon("E:\\bmwi8.jpg")); // NOI18N
        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(60, 70, 160, 115);

        jButton2.setIcon(new javax.swing.ImageIcon("E:\\bmwz4.jpg")); // NOI18N
        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(341, 69, 160, 115);

        jButton3.setForeground(new java.awt.Color(51, 0, 255));
        jButton3.setIcon(new javax.swing.ImageIcon("E:\\bmwX5.jpg")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(60, 240, 160, 115);

        jButton4.setIcon(new javax.swing.ImageIcon("E:\\bmw3.jpg")); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(341, 240, 160, 115);

        jButton5.setBackground(new java.awt.Color(255, 204, 102));
        jButton5.setForeground(new java.awt.Color(0, 153, 153));
        jButton5.setIcon(new javax.swing.ImageIcon("I:\\back.png")); // NOI18N
        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(230, 410, 98, 31);

        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("BMW i8");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(110, 200, 60, 14);

        jLabel2.setForeground(new java.awt.Color(0, 51, 255));
        jLabel2.setText("BMW Z4");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(401, 190, 50, 22);

        jLabel3.setForeground(new java.awt.Color(51, 0, 255));
        jLabel3.setText("BMW X5");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(110, 370, 50, 24);

        jLabel4.setForeground(new java.awt.Color(51, 0, 255));
        jLabel4.setText("BMW 3");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(409, 368, 50, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        JFrame f=new JFrame();
        JPanel p=new JPanel();
        p.setBounds(5,5,555,470);
        p.setBorder(BorderFactory.createLineBorder(Color.white));
        p.setBackground(Color.GRAY);
        Font fnt=new Font("Arial",Font.ITALIC,20);
        i1=new ImageIcon("C:\\Users\\user\\Pictures\\Screenshots\\bmw 3.png");
         JLabel l1=new JLabel("Specifications");
      l1.setBounds(230,5,140,30);
      f.add(l1);
      l1.setFont(fnt);
      l1.setForeground(Color.red);
      JLabel l2=new JLabel(i1);
      l2.setBounds(30,40,500,350);
      f.add(l2);
      JLabel l3=new JLabel("Rs 45.30lakh");
      l3.setBounds(220,410,150,50);
      f.add(l3);
      l3.setFont(fnt);
      l2.setVisible(true);
      JButton b1=new JButton("Place Order");
      b1.setBounds(50,420,120,40);
      f.add(b1);
      b1.addActionListener(new ActionListener(){
          public void actionPerformed(ActionEvent e)
          {
              str=jLabel4.getText();
              f.dispose();
              new order().setVisible(true);
              order.jLabel8.setText(str);
              
          }
      });
      JButton b2=new JButton("Back");
      b2.setBounds(400,420,120,40);
      f.add(b2);
      b2.addActionListener(new ActionListener(){
          public void actionPerformed(ActionEvent e)
          {
              f.dispose();
              new Secondpage().setVisible(true);
              
          }
      });
      f.add(p);
      f.setLayout(null);
      f.setVisible(true);
      f.setSize(580,520);
      f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Firstpage().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        JFrame f=new JFrame();
        JPanel p=new JPanel();
        p.setBounds(5,5,555,470);
        p.setBorder(BorderFactory.createLineBorder(Color.white));
        p.setBackground(Color.GRAY);
        Font fnt=new Font("Arial",Font.ITALIC,20);
        i1=new ImageIcon("C:\\Users\\user\\Pictures\\Screenshots\\bmw i8.png");
         JLabel l1=new JLabel("Specifications");
      l1.setBounds(230,5,140,30);
      f.add(l1);
      l1.setFont(fnt);
      l1.setForeground(Color.red);
      JLabel l2=new JLabel(i1);
      l2.setBounds(30,40,500,350);
      f.add(l2);
      JLabel l3=new JLabel("Rs 2.62Cr");
      l3.setBounds(220,410,150,50);
      f.add(l3);
      l3.setFont(fnt);
      System.out.println(l3.getText());
      l2.setVisible(true);
      JButton b1=new JButton("Place Order");
      b1.setBounds(50,420,120,40);
      f.add(b1);
      b1.addActionListener(new ActionListener(){
          public void actionPerformed(ActionEvent e)
          {
              str=jLabel1.getText();
              f.dispose();
              new order().setVisible(true);
              order.jLabel8.setText(str);
              
          }
      });
      JButton b2=new JButton("Back");
      b2.setBounds(400,420,120,40);
      f.add(b2);
      b2.addActionListener(new ActionListener(){
          public void actionPerformed(ActionEvent e)
          {
              f.dispose();
              new Secondpage().setVisible(true);
              
          }
      });
      f.add(p);
      f.setLayout(null);
      f.setVisible(true);
      f.setSize(580,520);
      f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        JFrame f=new JFrame();
        JPanel p=new JPanel();
        p.setBounds(5,5,555,470);
        p.setBorder(BorderFactory.createLineBorder(Color.white));
        p.setBackground(Color.GRAY);
        Font fnt=new Font("Arial",Font.ITALIC,20);
        i1=new ImageIcon("C:\\Users\\user\\Pictures\\Screenshots\\bmw Z4.png");
         JLabel l1=new JLabel("Specifications");
      l1.setBounds(230,5,140,30);
      f.add(l1);
      l1.setFont(fnt);
      l1.setForeground(Color.red);
      JLabel l2=new JLabel(i1);
      l2.setBounds(30,40,500,350);
      f.add(l2);
      JLabel l3=new JLabel("Rs 82.00lakh");
      l3.setBounds(220,410,150,50);
      f.add(l3);
      l3.setFont(fnt);
      l2.setVisible(true);
      JButton b1=new JButton("Place Order");
      b1.setBounds(50,420,120,40);
      f.add(b1);
      b1.addActionListener(new ActionListener(){
          public void actionPerformed(ActionEvent e)
          {
              str=jLabel2.getText();
              f.dispose();
              new order().setVisible(true);
              order.jLabel8.setText(str);
              
          }
      });
      JButton b2=new JButton("Back");
      b2.setBounds(400,420,120,40);
      f.add(b2);
      b2.addActionListener(new ActionListener(){
          public void actionPerformed(ActionEvent e)
          {
              f.dispose();
              new Secondpage().setVisible(true);
              
          }
      });
      f.add(p);
      f.setLayout(null);
      f.setVisible(true);
      f.setSize(580,520);
      f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        JFrame f=new JFrame();
        JPanel p=new JPanel();
        p.setBounds(5,5,555,470);
        p.setBorder(BorderFactory.createLineBorder(Color.white));
        p.setBackground(Color.GRAY);
        Font fnt=new Font("Arial",Font.ITALIC,20);
        i1=new ImageIcon("C:\\Users\\user\\Pictures\\Screenshots\\bmw X5.png");
         JLabel l1=new JLabel("Specifications");
      l1.setBounds(230,5,140,30);
      f.add(l1);
      l1.setFont(fnt);
      l1.setForeground(Color.red);
      JLabel l2=new JLabel(i1);
      l2.setBounds(30,40,500,350);
      f.add(l2);
      JLabel l3=new JLabel("Rs 75.80lakh");
      l3.setBounds(220,410,150,50);
      f.add(l3);
      l3.setFont(fnt);
      l2.setVisible(true);
      JButton b1=new JButton("Place Order");
      b1.setBounds(50,420,120,40);
      f.add(b1);
      b1.addActionListener(new ActionListener(){
          public void actionPerformed(ActionEvent e)
          {
              str=jLabel3.getText();
              f.dispose();
              new order().setVisible(true);
              order.jLabel8.setText(str);
              
          }
      });
      JButton b2=new JButton("Back");
      b2.setBounds(400,420,120,40);
      f.add(b2);
      b2.addActionListener(new ActionListener(){
          public void actionPerformed(ActionEvent e)
          {
              f.dispose();
              new Secondpage().setVisible(true);
              
          }
      });
      f.add(p);
      f.setLayout(null);
      f.setVisible(true);
      f.setSize(580,520);
      f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Secondpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Secondpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Secondpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Secondpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Secondpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
